catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  typescript: npm:typescript-native-bridge@latest
overrides:
  vite: 'catalog:'
  typescript: 'catalog:'
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
